# Provide definitions ahead of including Master Makefile
################################################################################
$(info Set Project Definitions)
# Define the Project Path
PATH_PROJECT_DIR = $(wildcard ~)/Git/STM32/I2CTest/
# Define the Target Name
TARGET = i2c_test
# Include the Master Makefile
$(info Include Master Makefile)
include ../Makefile

