# Provide definitions ahead of including Master Makefile
################################################################################
$(info Set Project Definitions)
# Define the Project Path
PATH_PROJECT_DIR = $(wildcard ~)/Git/STM32/ClockConfig/
# Define the Target Name
TARGET = clock_config
# Include the Master Makefile
$(info Include Master Makefile)
include ../Makefile

